title: I like to program
email: iliketoprogram14@gmail.com
description: Personal website for side projects.
url: http://iliketoprogram.com
github_username: iliketoprogram14
repository: iliketoprogram14/ILikeToProgram
author: Randy Miller

excerpt_separator: <!--more-->
paginate: 8
future: false
exclude: ["*.sh", "*.yml", README.md, .travis.yml, vendor, Gemfile, Gemfile.lock, ".vscode/*"]
gems: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
sass:
  sass_dir: _sass
  style: compressed
feed:
  path: atom.xml
  
# Once jekyll-seo-tag supports image objects, we can start using it and get rid of the schema* includes
#logo: /assets/images/publisher_logo.png
#defaults:
#  - scope:
#      path: ""
#    values:
#      image:
#        path: "https://iliketoprogram.com/assets/images/post_img.png"
#        height: 100
#        width: 700
