title: I like to program
email: iliketoprogram14@gmail.com
description: Personal website for side projects.
url: https://iliketoprogram.com
github_username: iliketoprogram14
repository: iliketoprogram14/ILikeToProgram
author: Randy Miller

excerpt_separator: <!--more-->
paginate: 8
future: false
exclude: ["*.sh", "*.yml", README.md, .travis.yml, vendor, Gemfile, Gemfile.lock, ".vscode/*"]
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
sass:
  sass_dir: _sass
  style: compressed
feed:
  path: atom.xml