# _config.yml
excerpt_separator: <!--more-->
paginate: 5
exclude: ["*.sh", "README.md", ".travis.yml", vendor]
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-tidy
sass:
  sass_dir: _sass
  style: compressed